//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing_entityfream_work.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDBEntities : DbContext
    {
        public TestDBEntities()
            : base("name=TestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOOKUPRole> LOOKUPRoles { get; set; }
        public virtual DbSet<SYSUser> SYSUsers { get; set; }
        public virtual DbSet<SysUserProfile> SysUserProfiles { get; set; }
        public virtual DbSet<SysUserRole> SysUserRoles { get; set; }

        public System.Data.Entity.DbSet<Testing_entityfream_work.Models.ViewModel.UserSignUpView> UserSignUpViews { get; set; }

        public System.Data.Entity.DbSet<Testing_entityfream_work.Models.ViewModel.UserLoginView> UserLoginViews { get; set; }

        public System.Data.Entity.DbSet<Testing_entityfream_work.Models.ViewModel.UserProfileView> UserProfileViews { get; set; }
    }
}
